name: "SEQ_Bundaberg_Goondiwini_ROI"
geojson_path: "data/roi/roi.geojson"
wkt_path: "data/roi/roi.wkt"

anchor_places:
    - Brisbane
    - Gympie
    - Sunshine Coast
    - Toowoomba
    - Warwick
    - Bundaberg
    - Goondiwini

buffer_kms: 50