"""Markdown report renderers for manifest and dataset-split stages.

Each function returns a markdown string; writing to disk is left to the caller so the
same renderer can be unit-tested without touching the filesystem.
"""

from __future__ import annotations

from bird_core.schemas import DatasetSplit

from bird_data.licensing import LICENSE_LABELS, is_open_license, license_counts
from bird_data.manifest_build import class_counts, find_duplicates
from bird_data.manifests import ImageManifestRecord
from bird_data.splits import ValidationIssue, split_records

_DISCLAIMER = (
    "> Generated by the BIRDIDEX dry-run pipeline. Counts reflect metadata only; no "
    "media has been retrieved unless an explicit retrieval command was run."
)


def render_license_report(records: list[ImageManifestRecord]) -> str:
    counts = license_counts(records)
    open_n = sum(1 for r in records if is_open_license(r.license))
    lines = [
        "# Licence Report",
        "",
        _DISCLAIMER,
        "",
        f"- Total records: **{len(records)}**",
        f"- Open-licensed (eligible): **{open_n}**",
        f"- Non-open / unknown: **{len(records) - open_n}**",
        "",
        "| Licence | Count | Eligible |",
        "| --- | ---: | :---: |",
    ]
    for code, n in counts.items():
        label = LICENSE_LABELS.get(code, code)
        eligible = "yes" if is_open_license(code) else "no"
        lines.append(f"| {label} | {n} | {eligible} |")
    return "\n".join(lines) + "\n"


def render_class_balance_report(records: list[ImageManifestRecord]) -> str:
    counts = class_counts(records)
    lines = [
        "# Class Balance Report",
        "",
        _DISCLAIMER,
        "",
        f"- Classes: **{len(counts)}**",
        f"- Total images: **{sum(counts.values())}**",
        "",
        "| Species | Images |",
        "| --- | ---: |",
    ]
    for name, n in sorted(counts.items(), key=lambda kv: (-kv[1], kv[0])):
        lines.append(f"| {name} | {n} |")
    if counts:
        hi, lo = max(counts.values()), min(counts.values())
        ratio = hi / lo if lo else float("inf")
        lines += ["", f"Imbalance ratio (max/min): **{ratio:.1f}**"]
    return "\n".join(lines) + "\n"


def render_duplicate_audit(records: list[ImageManifestRecord]) -> str:
    dups = find_duplicates(records)
    lines = [
        "# Duplicate Audit",
        "",
        _DISCLAIMER,
        "",
        f"- Exact-duplicate groups found: **{len(dups)}**",
        "",
        "_Near-duplicate (perceptual-hash) detection is a TODO — it requires the optional "
        "vision dependencies and the retrieved media files._",
        "",
    ]
    if dups:
        lines += ["| Duplicate key | Image ids |", "| --- | --- |"]
        for key, group in sorted(dups.items()):
            lines.append(f"| `{key}` | {', '.join(group)} |")
    else:
        lines.append("No exact duplicates detected.")
    return "\n".join(lines) + "\n"


def render_split_report(
    records: list[ImageManifestRecord],
    *,
    group_field: str,
    issues: list[ValidationIssue],
) -> str:
    buckets = split_records(records)
    lines = [
        "# Dataset Split Report",
        "",
        _DISCLAIMER,
        "",
        f"- Grouping field (leakage guard): **{group_field}**",
        "",
        "| Split | Images | Classes |",
        "| --- | ---: | ---: |",
    ]
    for split in (DatasetSplit.train, DatasetSplit.val, DatasetSplit.test, DatasetSplit.review):
        recs = buckets[split]
        n_classes = len({r.scientific_name for r in recs})
        lines.append(f"| {split.value} | {len(recs)} | {n_classes} |")

    errors = [i for i in issues if i.level == "error"]
    warnings = [i for i in issues if i.level == "warning"]
    lines += ["", f"## Validation: {len(errors)} error(s), {len(warnings)} warning(s)", ""]
    if not issues:
        lines.append("No validation issues detected.")
    for issue in issues:
        lines.append(f"- **[{issue.level}]** `{issue.code}` — {issue.message}")
    return "\n".join(lines) + "\n"
