"""ROI species-candidate scan pipeline.

Dry-run mode (the default) uses the deterministic local seed species list and their
synthetic evidence profiles — no provider requests, no network. A live run replaces the
seed profiles with occurrences parsed from provider responses (see the provider modules'
``parse_occurrences`` functions and :mod:`bird_roi_scan.occurrences`).

Outputs:
* ``data/manifests/roi_species_candidates.csv``
* ``data/manifests/species_priority_tiers.csv``
* ``data/reports/roi_species_candidates_report.md``
"""

from __future__ import annotations

import csv
from dataclasses import dataclass
from pathlib import Path

from bird_core.paths import get_manifests_dir, get_reports_dir

from bird_roi_scan.scoring import ScoredSpecies, ScoringConfig, SpeciesEvidence, score_all
from bird_roi_scan.seeds import SeedSpecies, seed_species

CANDIDATES_CSV_FIELDS: list[str] = [
    "species_id",
    "scientific_name",
    "common_name",
    "ebird_code",
    "total_occurrences",
    "n_sources",
    "occurrence",
    "source_agreement",
    "recency",
    "roi_match",
    "seasonal",
    "final_score",
    "tier",
    "status",
    "manual_review",
]

TIER_ORDER = ["core", "review", "rejected"]


@dataclass
class ScanResult:
    scored: list[ScoredSpecies]
    candidates_csv: Path
    tiers_csv: Path
    report_md: Path


def seed_to_evidence(seed: SeedSpecies) -> SpeciesEvidence:
    """Convert a seed's synthetic profile into scoring evidence (dry-run)."""
    return SpeciesEvidence(
        species_id=seed.species_id,
        scientific_name=seed.scientific_name,
        common_name=seed.common_name,
        ebird_code=seed.ebird_code,
        occurrences_by_source=dict(seed.occurrences_by_source),
        months_observed=set(seed.months_observed),
        inside_roi_fraction=seed.inside_roi_fraction,
        recent_years=set(seed.recent_years),
        manual_review=seed.manual_review,
    )


def _candidate_row(s: ScoredSpecies) -> dict[str, str]:
    return {
        "species_id": str(s.species_id),
        "scientific_name": s.scientific_name,
        "common_name": s.common_name or "",
        "ebird_code": s.ebird_code or "",
        "total_occurrences": str(s.total_occurrences),
        "n_sources": str(s.n_sources),
        "occurrence": f"{s.components['occurrence']:.4f}",
        "source_agreement": f"{s.components['source_agreement']:.4f}",
        "recency": f"{s.components['recency']:.4f}",
        "roi_match": f"{s.components['roi_match']:.4f}",
        "seasonal": f"{s.components['seasonal']:.4f}",
        "final_score": f"{s.final_score:.4f}",
        "tier": s.tier,
        "status": s.status.value,
        "manual_review": "true" if s.manual_review else "false",
    }


def write_candidates_csv(scored: list[ScoredSpecies], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as fh:
        writer = csv.DictWriter(fh, fieldnames=CANDIDATES_CSV_FIELDS)
        writer.writeheader()
        for s in scored:
            writer.writerow(_candidate_row(s))


def write_tiers_csv(scored: list[ScoredSpecies], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    order = {t: i for i, t in enumerate(TIER_ORDER)}
    ranked = sorted(
        scored, key=lambda s: (order.get(s.tier, 99), -s.final_score, s.scientific_name)
    )
    with path.open("w", encoding="utf-8", newline="") as fh:
        writer = csv.writer(fh)
        writer.writerow(["tier", "rank", "species_id", "scientific_name", "final_score"])
        for rank, s in enumerate(ranked, start=1):
            writer.writerow(
                [s.tier, rank, str(s.species_id), s.scientific_name, f"{s.final_score:.4f}"]
            )


def render_candidate_report(scored: list[ScoredSpecies], *, dry_run: bool) -> str:
    tier_counts = {t: sum(1 for s in scored if s.tier == t) for t in TIER_ORDER}
    lines = [
        "# ROI Species Candidates Report",
        "",
        "> Generated by the BIRDIDEX ROI scan pipeline"
        + (" in **dry-run** mode (deterministic local seed list; no provider requests)." if dry_run
           else " from parsed provider evidence."),
        "",
        f"- Species evaluated: **{len(scored)}**",
        f"- Core (accepted): **{tier_counts['core']}**",
        f"- Review: **{tier_counts['review']}**",
        f"- Rejected: **{tier_counts['rejected']}**",
        "",
        "## Ranked candidates",
        "",
        "| Species | Common | Occ. | Sources | Score | Tier |",
        "| --- | --- | ---: | ---: | ---: | --- |",
    ]
    for s in scored:
        lines.append(
            f"| _{s.scientific_name}_ | {s.common_name or ''} | {s.total_occurrences} | "
            f"{s.n_sources} | {s.final_score:.3f} | {s.tier} |"
        )
    lines += [
        "",
        "## Method",
        "",
        "Scores blend log-scaled occurrence volume, source agreement, recency, ROI match, "
        "and seasonal breadth. Manual-review species are routed to the review tier and are "
        "never hard-rejected, so rare or vagrant species survive for human inspection.",
        "",
        "_This report describes candidate prioritisation only. It makes no claim about any "
        "trained model's accuracy._",
    ]
    return "\n".join(lines) + "\n"


def run_candidate_scan(
    *,
    scoring_config: Path | None = None,
    manifests_dir: Path | None = None,
    reports_dir: Path | None = None,
    current_year: int | None = None,
    dry_run: bool = True,
) -> ScanResult:
    """Run the ROI candidate scan and write all outputs. Dry-run by default."""
    if not dry_run:
        raise NotImplementedError(
            "Live scan requires explicit provider requests — run the provider commands first "
            "and pass parsed evidence. Dry-run mode is the only offline path."
        )
    config = ScoringConfig.from_yaml(scoring_config) if scoring_config else ScoringConfig.defaults()
    evidences = [seed_to_evidence(s) for s in seed_species()]
    scored = score_all(evidences, config, current_year=current_year)

    manifests = manifests_dir or get_manifests_dir()
    reports = reports_dir or get_reports_dir()
    candidates_csv = manifests / "roi_species_candidates.csv"
    tiers_csv = manifests / "species_priority_tiers.csv"
    report_md = reports / "roi_species_candidates_report.md"

    write_candidates_csv(scored, candidates_csv)
    write_tiers_csv(scored, tiers_csv)
    report_md.parent.mkdir(parents=True, exist_ok=True)
    report_md.write_text(render_candidate_report(scored, dry_run=dry_run), encoding="utf-8")

    return ScanResult(scored, candidates_csv, tiers_csv, report_md)


def run_scan(
    roi_geojson: Path,
    providers: list[object],
    species_seed: Path | None = None,
) -> None:
    """Deprecated stub kept for import compatibility — use run_candidate_scan()."""
    raise NotImplementedError("run_scan is superseded by run_candidate_scan()")
